kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      name: python-pod
      labels:
        app: python
    spec:
      containers:
        - name: python-container
          image: <ECR_URL>:latest
          ports:
            - containerPort: 5000

